#include "standardlibs.h"
#include "structures.h"
#include "helper-functions.h"

/**
 * Prints the distances of vertices from a given source vertex in a spanning tree.
 *
 * @param current_spanning_tree The spanning tree containing the vertex distances.
 * @param source The source vertex.
 */
void print_distances(spanning_tree* current_spanning_tree, size_t source) {
    for (size_t i = 0; i < GRAPH_SIZE; ++i) {
        if (i == source) {
            continue;
        }
        else if (current_spanning_tree->vertex_distances[i] != SIZE_MAX) {
            printf("Vertex %zu is at a distance %zu from vertex %zu\n", i, current_spanning_tree->vertex_distances[i], source);
        } else {
            printf("Vertex %zu is not connected to vertex %zu\n", i, source);
        }
    }
}

/**
 * Frees the memory allocated for the graph, current queue, current spanning tree, and exploration forest.
 *
 * @param graph The adjacency matrix representing the graph.
 * @param curr_queue The queue used for breadth-first search.
 * @param current_spanning_tree The current spanning tree of the graph.
 * @param explor_forest The exploration forest of the graph.
 */
void free_variables(bool** graph, breadth_queue* curr_queue, spanning_tree* current_spanning_tree, exploration_forest* explor_forest) {
    for (int i = 0; i < GRAPH_SIZE; ++i) {
        free(graph[i]);
    }
    free(graph);
    free(curr_queue);
    free(current_spanning_tree);
    free(explor_forest);
}

/**
 * Prints the adjacency matrix of the exploration forest graph.
 *
 * @param explor_forest The exploration forest containing the graph.
 */
void print_forest_graph(exploration_forest* explor_forest) {
    for (int i = 0; i < GRAPH_SIZE; ++i) {
        for (int j = 0; j < GRAPH_SIZE; ++j) {
            printf("%d ", (explor_forest->forest_graph)[i][j]);
        }
        printf("\n");
    }
}

/**
 * Prints the adjacency matrix representation of a graph.
 *
 * @param graph The adjacency matrix representing the graph.
 */
void print_graph(bool** graph) {
    for (int i = 0; i < GRAPH_SIZE; ++i) {
        for (int j = 0; j < GRAPH_SIZE; ++j) {
            printf("%d ", (graph)[i][j]);
        }
        printf("\n");
    }
    printf("\n");
}

/**
 * Prints the result of the breadth-first search algorithm.
 * 
 * The result printed includes the original graph, the number of connected components, 
 * the source vertices used for breadth-first search, and the adjacency matrix of the exploration forest.
 *
 * @param graph The original graph represented by an adjacency matrix.
 * @param my_forest The exploration forest containing information about the connected components.
 * @param current_spanning_tree The current spanning tree generated by breadth-first search.
 * @param curr_queue The breadth-first search queue.
 */
void print_result(bool** graph, exploration_forest* my_forest, spanning_tree* current_spanning_tree, breadth_queue* curr_queue) {
    printf("The original graph can be represented by the following adjacency matrix:\n\n");
    print_graph(graph);
    
    printf("There are %zu connected components\n", my_forest->connected_components);

    printf("Here, breadth-first search was conducted on the following source vertices (each of which belongs to a different connected component): ");
    for (int i = 0; i< my_forest->connected_components-1; i++) {
        printf("%zu, ", my_forest->source_vertices[i]);
    }
    printf("%zu\n", my_forest->source_vertices[my_forest->connected_components -1]);
    
    printf("These %zu searches led to the following adjacency matrix for a corresponding spanning forest matrix (combination of %zu spanning trees generated by breadth-first search):\n\n", my_forest->connected_components,my_forest->connected_components);
    print_forest_graph(my_forest);
}